## Dubbo 服务提供者配置
dubbo:
  application:
    name: app-iotbmp-provider # 服务名
  registry:
    address: 106.15.201.55:2181,106.15.201.55:2182,106.15.201.55:2183 # 注册中心地址
    protocol: zookeeper
  protocol:
    name: dubbo # 指定通信协议
    port: 20880 # 通信端口  这里指的是与消费者间的通信协议与端口
  provider:
    timeout: 10000 # 配置全局调用服务超时时间，dubbo默认是1s，肯定不够用呀
    retries: 3 # 重试3次
    delay: -1
    version: 1.0.0

